require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'GroceriesApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'

  pod 'react-native-pager-view', :path => '../node_modules/react-native-pager-view'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  target 'GroceriesAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'GroceriesApp-tvOS' do
  # Pods for GroceriesApp-tvOS

  target 'GroceriesApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
